### ISSUE TITLE
I/O Error

### ISSUE THREAD

**Issue by jiwpark00** [dziq/biopython#1]
Hi, I'm learning Flask and trying to run your Biopython script. I'm getting an error, however as below (most recent call):

`File "/anaconda/lib/python2.7/site-packages/werkzeug/datastructures.py", line 2653, in save

```
                        :func:`shutil.copyfileobj`.
    """
    from shutil import copyfileobj
    close_dst = False
    if isinstance(dst, string_types):
        dst = open(dst, 'wb')
        close_dst = True
    try:
        copyfileobj(self.stream, dst, buffer_size)
    finally:
        if close_dst:
```

IOError: [Errno 2] No such file or directory: u'uploads/2016-09-23-10-43.fasta'`

I uploaded the file that you recommended (bovine), and it's in FASTA format and all but something is giving me an error...any idea?

This is from running it locally (localhost)

**Comment by dziq** [comment]
Show me your project (directory) structure. Do you have uploads folder?

**Comment by jiwpark00** [comment]
Ooh... Nope. I didn't make a separate uploads folder. I just made one, and it now works.

So uploads file is needed to store all the input, it seems like. Got it.
